const ACTION_TYPES = {
  GET_MESSAGES_ACTION: 'GET_MESSAGES_ACTION',
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_ACTION',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',

  NEW_MESSAGE_ACTION: 'NEW_MESSAGE_ACTION',
  NEW_MESSAGE_REQUEST: 'NEW_MESSAGE_REQUEST',
  NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
  NEW_MESSAGE_ERROR: 'NEW_MESSAGE_ERROR',
};
export default ACTION_TYPES;
